ServiceHost/Areas/Administration/Pages/Blog/Article/Create.cshtml.cs
using BlogMgmt.Application.Contract.Article;
using BlogMgmt.Application.Contract.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Blog.Article;
#nullable disable

public class CreateModel : PageModel
{
    private readonly IArticleApplication _articleApplication;
    private readonly IArticleCategoryApplication _articleCategoryApplication;

    public CreateArticle Command { get; set; }
    public SelectList ArticleCategories { get; set; }

    public CreateModel(IArticleCategoryApplication articleCategoryApplication, 
        IArticleApplication articleApplication)
    {
        _articleCategoryApplication = articleCategoryApplication;
        _articleApplication = articleApplication;
    }

    public void OnGet()
    {
        ArticleCategories = new SelectList(_articleCategoryApplication.GetCategories(), "Id", "Name");
    }

    public async Task<IActionResult> OnPost(CreateArticle command)
    {
        var result = await _articleApplication.Create(command);
        return RedirectToPage("./Index");
    }
}

ServiceHost/Areas/Administration/Pages/Blog/Article/Edit.cshtml.cs
using BlogMgmt.Application.Contract.Article;
using BlogMgmt.Application.Contract.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Blog.Article;
#nullable disable

public class EditModel : PageModel
{
    private readonly IArticleApplication _articleApplication;
    private readonly IArticleCategoryApplication _articleCategoryApplication;

    public EditArticle Command { get; set; }
    public SelectList ArticleCategories { get; set; }

    public EditModel(IArticleApplication articleApplication,
        IArticleCategoryApplication articleCategoryApplication)
    {
        _articleApplication = articleApplication;
        _articleCategoryApplication = articleCategoryApplication;
    }

    public void OnGet(long id)
    {
        Command = _articleApplication.GetDetails(id);
        ArticleCategories = new SelectList(_articleCategoryApplication.GetCategories(), "Id", "Name");
    }

    public async Task<IActionResult> OnPost(EditArticle command)
    {
        var result = await _articleApplication.Edit(command);
        return RedirectToPage("./Index");
    }
}

ServiceHost/Areas/Administration/Pages/Blog/Article/Index.cshtml.cs
using BlogMgmt.Application.Contract.Article;
using BlogMgmt.Application.Contract.ArticleCategory;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Blog.Article;

public class IndexModel : PageModel
{
    private readonly IArticleCategoryApplication _articleCategoryApplication;
    private readonly IArticleApplication _articleApplication;

    public List<ArticleViewModel>? Articles { get; set; }
    public SelectList? ArticleCategories { get; set; }
    public ArticleSearchModel? SearchModel { get; set; }

    public IndexModel(IArticleCategoryApplication articleCategoryApplication,
        IArticleApplication articleApplication)
    {
        _articleCategoryApplication = articleCategoryApplication;
        _articleApplication = articleApplication;
    }

    public void OnGet(ArticleSearchModel searchModel)
    {
        ArticleCategories = new SelectList(_articleCategoryApplication.GetCategories(), "Id", "Name");
        Articles = _articleApplication.Search(searchModel);
    }
}

ServiceHost/Areas/Administration/Pages/Blog/ArticleCategory/Index.cshtml.cs
using _Framework.Application;
using BlogMgmt.Application.Contract.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Areas.Administration.Pages.Blog.ArticleCategory;

public class IndexModel : PageModel
{
    private readonly IArticleCategoryApplication _articleCategoryApplication;
    public List<ArticleCategoryViewModel>? ArticleCategories { get; set; }
    public ArticleCategorySearchModel? SearchModel { get; set; }

    public IndexModel(IArticleCategoryApplication articleCategoryApplication)
    {
        _articleCategoryApplication = articleCategoryApplication;
    }

    public void OnGet(ArticleCategorySearchModel searchModel)
    {
        ArticleCategories = _articleCategoryApplication.Search(searchModel);
    }

    public IActionResult OnGetCreate()
    {
        return Partial("./Create", new CreateArticleCategory());
    }

    public async Task<JsonResult> OnPostCreate(CreateArticleCategory command)
    {
        if (!ModelState.IsValid)
        {
            var failed = new OperationResult();
            failed.Message = "پر کردن تمام فیلدها الزامی است";
            return new JsonResult(failed);
        }
        var result = await _articleCategoryApplication.Create(command);
        if (result.IsSucceeded)
        {
            TempData["ArticleCategorySubmission"] = result.Message;
        }
        return new JsonResult(result);
    }

    public IActionResult OnGetEdit(long id)
    {
        var articleCategory = _articleCategoryApplication.GetDetails(id);
        return Partial("./Edit", articleCategory);
    }

    public async Task<IActionResult> OnPostEdit(EditArticleCategory command)
    {
        // validation in case client side fail on picture
        if (!ModelState.IsValid)
        {
            command.Picture = null;
        }

        var result = await _articleCategoryApplication.Edit(command);
        if (result.IsSucceeded)
        {
            TempData["ArticleCategoryEdition"] = result.Message;
        }
        return new JsonResult(result);
    }
}

ServiceHost/Areas/Administration/Pages/Shop/Product/Index.cshtml.cs
using _Framework.Application;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopMgmt.Application.Contract.Product;
using ShopMgmt.Application.Contract.ProductCategory;

namespace ServiceHost.Areas.Administration.Pages.Shop.Product;

public class IndexModel : PageModel
{
    private readonly IProductApplication _productApplication;
    private readonly IProductCategoryApplication _productCategoryApplication;

    public IEnumerable<ProductViewModel>? Products { get; set; }
    public ProductSearchModel? SearchModel { get; set; }
    public SelectList? ProductCategories { get; set; }

    public IndexModel(IProductApplication productApplication, 
        IProductCategoryApplication productCategoryApplication)
    {
        _productApplication = productApplication;
        _productCategoryApplication = productCategoryApplication;
    }

    public void OnGet(ProductSearchModel searchModel)
    {
        ProductCategories = new SelectList(_productCategoryApplication.GetProductCategories(), "Id", "Name");
        Products = _productApplication.Search(searchModel);
    }

    public IActionResult OnGetCreate()
    {
        var createProduct = new CreateProduct() { ProductCategories = _productCategoryApplication.GetProductCategories() };
        return Partial("./Create", createProduct);
    }

    public async Task<JsonResult> OnPostCreate(CreateProduct command)
    {
        if (!ModelState.IsValid)
        {
            var failed = new OperationResult();
            failed.Message = "پر کردن تمام فیلدها الزامی است";
            return new JsonResult(failed);
        }
        var result = await _productApplication.Create(command);
        if (result.IsSucceeded)
        {
            TempData["ProductSubmission"] = result.Message;
        }
        return new JsonResult(result);
    }

    public IActionResult OnGetEdit(long id)
    {
        var product = _productApplication.GetDetails(id);
        product.ProductCategories = _productCategoryApplication.GetProductCategories();
        return Partial("./Edit", product);
    }

    public async Task<IActionResult> OnPostEdit(EditProduct command)
    {
        var result = await _productApplication.Edit(command);
        if (result.IsSucceeded)
        {
            TempData["ProductEdition"] = result.Message;
        }
        return new JsonResult(result);
    }
}

ServiceHost/Areas/Administration/Pages/Shop/ProductCategory/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShopMgmt.Application.Contract.ProductCategory;
using ShopMgmt.Domain.ProductCategoryAgg;

namespace ServiceHost.Areas.Administration.Pages.Shop.ProductCategory;

public class IndexModel : PageModel
{
    private readonly IProductCategoryApplication _productCategoryApplication;
    public IEnumerable<ProductCategoryViewModel>? ProductCategories { get; set; }
    public ProductCategorySearchModel? SearchModel { get; set; }

    public IndexModel(IProductCategoryApplication productCategoryApplication)
    {
        _productCategoryApplication = productCategoryApplication;
    }

    public void OnGet(ProductCategorySearchModel searchModel)
    {
        ProductCategories = _productCategoryApplication.Search(searchModel);
    }

    public IActionResult OnGetCreate()
    {
        return Partial("./Create", new CreateProductCategory());
    }

    public async Task<JsonResult> OnPostCreate(CreateProductCategory command)
    {
        var result = await _productCategoryApplication.Create(command);
        if (result.IsSucceeded)
        {
            TempData["ProductCategorySubmission"] = result.Message;
        }
        return new JsonResult(result);
    }

    public IActionResult OnGetEdit(long id)
    {
        var productCategory = _productCategoryApplication.GetDetails(id);
        return Partial("./Edit", productCategory);
    }

    public async Task<IActionResult> OnPostEdit(EditProductCategory command)
    {
        // validation in case client side fail on picture
        if (!ModelState.IsValid)
        {
            command.Picture = null;
        }

        var result = await _productCategoryApplication.Edit(command);
        if (result.IsSucceeded)
        {
            TempData["ProductCategoryEdition"] = result.Message;
        }
        return new JsonResult(result);
    }
}

ServiceHost/Areas/Administration/Pages/UserAccount/Account/Index.cshtml.cs
using _Framework.Application;
using AccountMgmt.Application.Contract.Account;
using AccountMgmt.Application.Contract.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.UserAccount.Account;
#nullable disable

public class IndexModel : PageModel
{
    private readonly IAccountApplication _accountApplication;
    private readonly IRoleApplication _roleApplication;

    public List<AccountViewModel> Accounts { get; set; }
    public AccountSearchModel SearchModel { get; set; }
    public SelectList Roles { get; set; }

    public IndexModel(IAccountApplication accountApplication,
        IRoleApplication roleApplication)
    {
        _accountApplication = accountApplication;
        _roleApplication = roleApplication;
    }

    public void OnGet(AccountSearchModel searchModel)
    {
        Roles = new SelectList(_roleApplication.GetRoles(), "Id", "Name");
        Accounts = _accountApplication.Search(searchModel);
    }

    public IActionResult OnGetCreate()
    {
        var roles = _roleApplication.GetRoles();
        var model = new CreateAccount() { Roles = roles};
        return Partial("./Create", model);
    }

    public async Task<JsonResult> OnPostCreate(CreateAccount command)
    {
        if (!ModelState.IsValid)
        {
            var failed = new OperationResult();
            failed.Message = "پر کردن تمام فیلدها الزامی است";
            return new JsonResult(failed);
        }
        var result = await _accountApplication.Register(command);

        if (result.IsSucceeded)
        {
            TempData["AccountSubmission"] = result.Message;
        }

        return new JsonResult(result);
    }

    public IActionResult OnGetEdit(long id)
    {
        var account = _accountApplication.GetDetails(id);
        var roles = _roleApplication.GetRoles();
        account.Roles = roles;
        return Partial("./Edit", account);
    }

    public async Task<IActionResult> OnPostEdit(EditAccount command)
    {
        var result = await _accountApplication.Edit(command);

        if (result.IsSucceeded)
        {
            TempData["AccountEdition"] = result.Message;
        }

        return new JsonResult(result);
    }

    public IActionResult OnGetChangePassword(long id)
    {
        var passwdModel = new ChangePassword() { Id = id };
        return Partial("ChangePassword", passwdModel);
    }

    public IActionResult OnPostChangePassword(ChangePassword command)
    {
        var result = _accountApplication.ChangePassword(command);

        if (result.IsSucceeded)
        {
            TempData["PasswordChangeStatus"] = result.Message;
        }

        return new JsonResult(result);
    }
}

ServiceHost/Controllers/ProductController.cs
using _LampshadeQuery.Contract.Product;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ServiceHost.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class ProductController : ControllerBase
    {
        private readonly IProductQuery _productQuery;

        public ProductController(IProductQuery productQuery)
        {
            _productQuery = productQuery;
        }

        [HttpGet]
        public IEnumerable<ProductQueryModel> GetLatestProducts()
        {
            return _productQuery.GetLatestProducts();
        }
    }
}

ServiceHost/Pages/AccessDenied.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Pages
{
    public class AccessDeniedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ServiceHost/Pages/Account.cshtml.cs
using AccountMgmt.Application.Contract.Account;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Pages;
#nullable disable

public class AccountModel : PageModel
{
    private readonly IAccountApplication _accountApplication;

    public AccountModel(IAccountApplication accountApplication)
    {
        _accountApplication = accountApplication;
    }

    public void OnGet()
    {
    }

    public IActionResult OnPostLogin(Login command)
    {
        var result = _accountApplication.Login(command);

        if (!result.IsSucceeded)
        {
            ViewData["LoginErr"] = result.Message;
            ModelState.Clear();
            return Page();
        }

        return RedirectToPage("/Index");
    }

    public ActionResult OnGetLogout()
    {
        _accountApplication.Logout();
        return RedirectToPage("/Index");
    }

    public async Task<IActionResult> OnPostRegister(CreateAccount command)
    {

        var result = await _accountApplication.Register(command);

        if (!result.IsSucceeded)
        {
            ViewData["RegisterErr"] = result.Message;
            return Page();
        }

        return RedirectToPage("/Index");
    }
}

ServiceHost/Pages/EmptySearchItem.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Pages
{
    public class EmptySearchItemModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ServiceHost/ViewComponents/LatestArticlesViewComponent.cs
using _LampshadeQuery.Contract.Article;
using Microsoft.AspNetCore.Mvc;

namespace ServiceHost.ViewComponents;
#nullable disable

public class LatestArticlesViewComponent : ViewComponent
{
    private readonly IArticleQuery _articleQuery;

    public LatestArticlesViewComponent(IArticleQuery articleQuery)
    {
        _articleQuery = articleQuery;
    }

    public IViewComponentResult Invoke()
    {
        var articles = _articleQuery.GetLatestArticles();
        return View(articles);
    }
}

ServiceHost/ViewComponents/LatestProductsViewComponent.cs
using _LampshadeQuery.Contract.Product;
using Microsoft.AspNetCore.Mvc;

namespace ServiceHost.ViewComponents;

public class LatestProductsViewComponent : ViewComponent
{
    private readonly IProductQuery _productQuery;

    public LatestProductsViewComponent(IProductQuery productQuery)
    {
        _productQuery = productQuery;
    }

    public IViewComponentResult Invoke()
    {
        var products = _productQuery.GetLatestProducts();
        return View(products);
    }
}

ServiceHost/ViewComponents/ProductCategoryViewComponent.cs
using _LampshadeQuery.Contract.ProductCategory;
using Microsoft.AspNetCore.Mvc;

namespace ServiceHost.ViewComponents;
#nullable disable

public class ProductCategoryViewComponent : ViewComponent
{
    private readonly IProductCategoryQuery _productCategoryQuery;

    public ProductCategoryViewComponent(IProductCategoryQuery productCategoryQuery)
    {
        _productCategoryQuery = productCategoryQuery;
    }

    public IViewComponentResult Invoke()
    {
        var productCategories = _productCategoryQuery.GetProductCategories();
        return View(productCategories);
    }
}

ServiceHost/ViewComponents/SlideViewComponent.cs
using _LampshadeQuery.Contract.Slide;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;

namespace ServiceHost.ViewComponents;
#nullable disable

public class SlideViewComponent : ViewComponent
{
    private readonly ISlideQuery _slideQuery;

    public SlideViewComponent(ISlideQuery slideQuery)
    {
        _slideQuery = slideQuery;
    }

    public IViewComponentResult Invoke()
    {
        var slides = _slideQuery.GetSlides();
        return View(slides);
    }
}

ServiceHost/Pages/AccessDenied.cshtml
@page
@model ServiceHost.Pages.AccessDeniedModel

@{
    ViewData["Title"] = "عدم دسترسی";
}

<div class="page-content-area">
    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-12">
                <!--=======  shop page wrapper  =======-->
                <div class="page-wrapper">
                    <div class="page-content-wrapper">
                        <div class="row d-flex justify-content-center">
                            <div class="col-md-8">
                                <h2 class="text text-center text-danger">شما مجوز دسترسی به این قسمت را ندارید!</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ServiceHost/Pages/EmptySearchItem.cshtml
@page
@model ServiceHost.Pages.EmptySearchItemModel
@{
}

@{
    ViewData["Title"] = "موردی پیدا نشد";
}

<div class="page-content-area">
    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-12">
                <!--=======  shop page wrapper  =======-->
                <div class="page-wrapper">
                    <div class="page-content-wrapper">
                        <div class="row d-flex justify-content-center">
                            <div class="col-md-5">
                                <h3 class="text text-center text-warning">محصولی با این نام یا عبارت پیدا نشد</h3>
                                <img class="img-fluid" src="~/Theme/assets/img/products/emptySearch.jpg" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ServiceHost/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "پروژه تجارت الکترونیکی پوریا ضیامنش";
}


@await Component.InvokeAsync("Slide")

@await Component.InvokeAsync("ProductCategory")

@await Component.InvokeAsync("ProductCategoryWithProducts")

@await Component.InvokeAsync("LatestProducts")

<!--====================  banner hover area ====================-->
<div class="banner-hover-area section-space">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <!--=======  banner hover wrapper  =======-->
                <div class="banner-hover-wrapper">
                    <div class="row">
                        <div class="col-md-6">
                            <!--=======  single hover banner  =======-->
                            <div class="single-hover-banner">
                                <div class="single-hover-banner__image">
                                    <a href="shop-left-sidebar.html">
                                        <img src="~/Theme/assets/img/banners/img1-middle-eposi1.jpg" class="img-fluid"
                                             alt="">
                                    </a>
                                    <div class="single-hover-banner__content">
                                        <h4 class="small-text">Black Friday</h4>
                                        <h3 class="big-text">Save Up To 50% Off</h3>
                                        <a class="banner-link" href="shop-left-sidebar.html">SHOP NOW</a>
                                    </div>
                                </div>
                            </div>
                            <!--=======  End of single hover banner  =======-->
                        </div>

                        <div class="col-md-6">
                            <!--=======  single hover banner  =======-->
                            <div class="single-hover-banner">
                                <div class="single-hover-banner__image">
                                    <a href="shop-left-sidebar.html">
                                        <img src="~/Theme/assets/img/banners/img2-middle-eposi1.jpg" class="img-fluid"
                                             alt="">
                                    </a>
                                    <div class="single-hover-banner__content">
                                        <h4 class="small-text">Best Selling !</h4>
                                        <h3 class="big-text">Living Room Up To 70% Off</h3>
                                        <a class="banner-link" href="shop-left-sidebar.html">SHOP NOW</a>
                                    </div>
                                </div>
                            </div>
                            <!--=======  End of single hover banner  =======-->
                        </div>
                    </div>
                </div>
                <!--=======  End of banner hover wrapper  =======-->
            </div>
        </div>
    </div>
</div>

<!--====================  feature logo area ====================-->
<div class="feature-logo-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <!--=======  feature logo wrapper  =======-->
                <div class="feature-logo-wrapper section-space--inner-bottom">
                    <div class="row">
                        <div class="col-md-4">
                            <!--=======  single feature logo  =======-->
                            <div class="single-feature-logo">
                                <div class="single-feature-logo__image">
                                    <img src="~/Theme/assets/img/icons/free_shipping.png" class="img-fluid" alt="">
                                </div>
                                <div class="single-feature-logo__content">
                                    <h4 class="title">FREE SHIPPING WORLDWIDE</h4>
                                    <p class="short-desc">
                                        We offer free shipping via Standard Shipping on orders
                                        over $200.00
                                    </p>
                                </div>
                            </div>
                            <!--=======  End of single feature logo  =======-->
                        </div>
                        <div class="col-md-4">
                            <!--=======  single feature logo  =======-->
                            <div class="single-feature-logo">
                                <div class="single-feature-logo__image">
                                    <img src="~/Theme/assets/img/icons/money_back.png" class="img-fluid" alt="">
                                </div>
                                <div class="single-feature-logo__content">
                                    <h4 class="title">MONEY BACK GUARANTEE</h4>
                                    <p class="short-desc">
                                        If you're not satisfied with our product, we'll refund the
                                        purchase price*.
                                    </p>
                                </div>
                            </div>
                            <!--=======  End of single feature logo  =======-->
                        </div>
                        <div class="col-md-4">
                            <!--=======  single feature logo  =======-->
                            <div class="single-feature-logo">
                                <div class="single-feature-logo__image">
                                    <img src="~/Theme/assets/img/icons/support247.png" class="img-fluid" alt="">
                                </div>
                                <div class="single-feature-logo__content">
                                    <h4 class="title">ONLINE SUPPORT 24/7</h4>
                                    <p class="short-desc">
                                        Our friendly support team is available to help you 24
                                        hours a day, seven days a week
                                    </p>
                                </div>
                            </div>
                            <!--=======  End of single feature logo  =======-->
                        </div>
                    </div>
                </div>
                <!--=======  End of feature logo wrapper  =======-->
            </div>
        </div>
    </div>
</div>

@await Component.InvokeAsync("LatestArticles")

<!--====================  newsletter area ====================-->
<div class="newsletter-area section-space--inner">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 offset-lg-2">
                <div class="newsletter-wrapper">
                    <p class="small-text">Special Ofers For Subscribers</p>
                    <h3 class="title">Ten Percent Member Discount</h3>
                    <p class="short-desc">
                        Subscribe to our newsletters now and stay up to date with new collections,
                        the latest lookbooks and exclusive offers.
                    </p>

                    <div class="newsletter-form">
                        <form id="mc-form" class="mc-form">
                            <input type="email" placeholder="Enter Your Email Address Here..." required>
                            <button type="submit" value="submit">SUBSCRIBE</button>
                        </form>

                    </div>
                    <!-- mailchimp-alerts Start -->
                    <div class="mailchimp-alerts">
                        <div class="mailchimp-submitting"></div><!-- mailchimp-submitting end -->
                        <div class="mailchimp-success"></div><!-- mailchimp-success end -->
                        <div class="mailchimp-error"></div><!-- mailchimp-error end -->
                    </div>
                    <!-- mailchimp-alerts end -->
                </div>
            </div>
        </div>
    </div>
</div>