ServiceHost/Pages/Account.cshtml.cs
using AccountMgmt.Application.Contract.Account;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Pages;
#nullable disable

public class AccountModel : PageModel
{
    private readonly IAccountApplication _accountApplication;

    public AccountModel(IAccountApplication accountApplication)
    {
        _accountApplication = accountApplication;
    }

    public void OnGet()
    {
    }

    public IActionResult OnPostLogin(Login command)
    {
        var result = _accountApplication.Login(command);

        if (!result.IsSucceeded)
        {
            ViewData["LoginErr"] = result.Message;
            ModelState.Clear();
            return Page();
        }

        return RedirectToPage("/Index");
    }

    public ActionResult OnGetLogout()
    {
        _accountApplication.Logout();
        return RedirectToPage("/Index");
    }

    public async Task<IActionResult> OnPostRegister(CreateAccount command)
    {

        var result = await _accountApplication.Register(command);

        if (!result.IsSucceeded)
        {
            ViewData["RegisterErr"] = result.Message;
            return Page();
        }

        return RedirectToPage("/Index");
    }
}

ServiceHost/Areas/Administration/Pages/Shared/_SideBar.cshtml
@using AccountMgmt.Infrastructure.EFCore
@using _Framework.Application
@using _Framework.Infrastructure
@inject IAuthHelper _authHelper
@inject AccountContext _accountContext
@{
    var user = _authHelper.UserInfo();
    var profilePicture = _accountContext.Accounts
        .Select(x => new { x.Id, x.ProfilePhoto })
        .FirstOrDefault(x => x.Id == user.Id);
}

<div class="left side-menu">
    <div class="sidebar-inner slimscrollleft">
        <div class="user-details">
            <div class="pull-left">
                <img src="~/ProductPictures/@profilePicture.ProfilePhoto" alt="" class="thumb-md img-circle">
            </div>
            <div class="user-info">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">@user.UserName</a>
                <p class="text-muted m-0">@user.RoleMean()</p>
            </div>
        </div>
        <!--- Divider -->
        <div id="sidebar-menu">
            <ul>
                <li>
                    <a asp-area="" asp-page="/Index" class="waves-effect">
                        <i class="fa fa-laptop"></i><span> سایت </span>
                    </a>
                </li>
                <li>
                    <a asp-page="/Index" class="waves-effect">
                        <i class="fa fa-tachometer"></i><span> داشبورد </span>
                    </a>
                </li>
                @if (_authHelper.AuthorizedRole() == Roles.Admin)
                {
                    <li>
                        <a asp-page="/Inventory/Index" class="waves-effect">
                            <i class="md md-business"></i><span> انبارداری </span>
                        </a>
                    </li>
                }
                <li>
                    <a asp-page="/Comment/Index" class="waves-effect">
                        <i class="ion-chatbubbles"></i><span> کامنت ها </span>
                    </a>
                </li>
                @if (_authHelper.AuthorizedRole() == Roles.Admin)
                {
                    <li class="has_sub">
                        <a class="waves-effect">
                            <i class="md-shopping-cart"></i><span> فروشگاه </span>
                            <span class="pull-right">
                                <i class="md md-add"></i>
                            </span>
                        </a>
                        <ul class="list-unstyled">
                            <li>
                                <a asp-page="/Shop/ProductCategory/Index">گروه محصولات</a>
                            </li>
                            <li>
                                <a asp-page="/Shop/Product/Index">محصولات</a>
                            </li>
                            <li>
                                <a asp-page="/Shop/ProductPicture/Index">عکس محصولات</a>
                            </li>
                            <li>
                                <a asp-page="/Shop/Slide/Index">اسلایدها</a>
                            </li>
                        </ul>
                    </li>
                }
                @if (_authHelper.AuthorizedRole() == Roles.Admin)
                {
                    <li class="has_sub">
                        <a class="waves-effect">
                            <i class="md-loyalty"></i><span> تخفیفات </span>
                            <span class="pull-right">
                                <i class="md md-add"></i>
                            </span>
                        </a>
                        <ul class="list-unstyled">
                            <li>
                                <a asp-page="/Discount/CustomerDiscount/Index">تخفیف مشتریان</a>
                            </li>
                            <li>
                                <a asp-page="/Discount/ColleagueDiscount/Index">تخفیف همکاران</a>
                            </li>
                        </ul>
                    </li>
                }
                <li class="has_sub">
                    <a class="waves-effect">
                        <i class="ion-happy"></i><span> بلاگ </span>
                        <span class="pull-right">
                            <i class="md md-add"></i>
                        </span>
                    </a>
                    <ul class="list-unstyled">
                        <li>
                            <a asp-page="/Blog/ArticleCategory/Index">گروه مقالات</a>
                        </li>
                        <li>
                            <a asp-page="/Blog/Article/Index">مقالات</a>
                        </li>
                    </ul>
                </li>
                @if (_authHelper.AuthorizedRole() == Roles.Admin)
                {
                    <li class="has_sub">
                        <a class="waves-effect">
                            <i class="ion-android-social"></i><span> حساب کاربری </span>
                            <span class="pull-right">
                                <i class="md md-add"></i>
                            </span>
                        </a>
                        <ul class="list-unstyled">
                            <li>
                                <a asp-page="/UserAccount/Account/Index">کاربران</a>
                            </li>
                            <li>
                                <a asp-page="/UserAccount/Role/Index">نقش ها</a>
                            </li>
                        </ul>
                    </li>
                }
                <li>
                    <a asp-page="/Account" asp-page-handler="Logout">
                        <i class="md md-settings-power"></i><span> خروج </span>
                    </a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>