ServiceHost/Areas/Administration/Pages/Comment/Index.cshtml.cs
using CommentMgmt.Application.Contract.Comment;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Areas.Administration.Pages.Comment;
#nullable disable

public class IndexModel : PageModel
{
    private readonly ICommentApplication _commentApplication;
    public List<CommentViewModel> Comments { get; set; }
    public CommentSearchModel SearchModel { get; set; }

    public IndexModel(ICommentApplication commentApplication)
    {
        _commentApplication = commentApplication;
    }

    public void OnGet(CommentSearchModel searchModel)
    {
        Comments = _commentApplication.Search(searchModel);
    }
   
    public IActionResult OnGetConfirm(long id)
    {
        _commentApplication.Confirm(id);
        return RedirectToPage("./Index");
    }

    public IActionResult OnGetCancel(long id)
    {
        _commentApplication.Cancel(id);
        return RedirectToPage("./Index");
    }
}

ServiceHost/Areas/Administration/Pages/Shop/Comment/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShopMgmt.Application.Contract.Comment;

namespace ServiceHost.Areas.Administration.Pages.Shop.Comment;
#nullable disable

public class IndexModel : PageModel
{
    private readonly ICommentApplication _commentApplication;
    public List<CommentViewModel> Comments { get; set; }
    public CommentSearchModel SearchModel { get; set; }

    public IndexModel(ICommentApplication commentApplication)
    {
        _commentApplication = commentApplication;
    }

    public void OnGet(CommentSearchModel searchModel)
    {
        Comments = _commentApplication.Search(searchModel);
    }
   
    public IActionResult OnGetConfirm(long id)
    {
        _commentApplication.Confirm(id);
        return RedirectToPage("./Index");
    }

    public IActionResult OnGetCancel(long id)
    {
        _commentApplication.Cancel(id);
        return RedirectToPage("./Index");
    }
}

ServiceHost/Areas/Administration/Pages/Comment/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "مدیریت کامنت ها";
}

<div class="row">
    <div class="col-sm-12">

        <h4 class="page-title pull-right">@ViewData["Title"]</h4>

    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">جستجو در کامنت ها</h3>
            </div>
            <div class="panel-body">
                <form class="form-inline" role="form" method="get">
                    <div class="form-group">
                        <input class="form-control" asp-for="SearchModel.Name" placeholder="نام کاربر">
                    </div>
                    <div class="form-group">
                        <input class="form-control" asp-for="SearchModel.Email" placeholder="ایمیل">
                    </div>
                    <div class="form-group">
                        <button class="btn btn-success waves-effect waves-light m-l-10 m-r-10">جستجو</button>
                        <a class="btn btn-primary waves-effect waves-light m-l-10" asp-page="./Index">مشاهده همه</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">لیست کامنت ها (@Model.Comments.Count())</h3>
            </div>
            <div class="panel-body">

                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12 table-responsive">
                        <table data-order='[[ 0, "desc" ]]' id="datatable" class="table table-striped table-bordered ">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>نام</th>
                                    <th>ایمیل</th>
                                    <th>پیام</th>
                                    <th>تاریخ ایجاد</th>
                                    <th>وضعیت</th>
                                    <th>عملیات</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.Comments)
                                {
                                    <tr>
                                        <td>@item.Id</td>
                                        <td>@item.Name</td>
                                        <td>@item.Email</td>
                                        <td>@item.Message</td>
                                        <td>@item.CreationDate</td>

                                        <td class="text-center">

                                            @if (item.IsCanceled)
                                            {
                                                <span class="text-danger">لغو شده</span>
                                            }

                                            @if (!item.IsCanceled && !item.IsConfirmed)
                                            {
                                                <span class="text-warning">در انتظار</span>
                                            }

                                            @if (!item.IsCanceled && item.IsConfirmed)
                                            {
                                                <span class="text-success">تایید شده</span>
                                            }
                                        </td>

                                        <td>
                                            <a class="btn btn-success waves-effect waves-light m-b-5"
                                           asp-page="./Index"
                                           asp-page-handler="Confirm"
                                           asp-route-id="@item.Id">
                                                تایید
                                            </a>

                                            <a class="btn btn-danger waves-effect waves-light m-b-5"
                                           asp-page="./Index"
                                           asp-page-handler="Cancel"
                                           asp-route-id="@item.Id">
                                                لغو
                                            </a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/AdminTheme/assets/datatables/jquery.dataTables.min.js"></script>
    <script src="~/AdminTheme/assets/datatables/dataTables.bootstrap.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#datatable').dataTable();
        });
    </script>
}