ServiceHost/Areas/Administration/Pages/Blog/Article/Create.cshtml.cs
using BlogMgmt.Application.Contract.Article;
using BlogMgmt.Application.Contract.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Blog.Article;
#nullable disable

public class CreateModel : PageModel
{
    private readonly IArticleApplication _articleApplication;
    private readonly IArticleCategoryApplication _articleCategoryApplication;

    public CreateArticle Command { get; set; }
    public SelectList ArticleCategories { get; set; }

    public CreateModel(IArticleCategoryApplication articleCategoryApplication, 
        IArticleApplication articleApplication)
    {
        _articleCategoryApplication = articleCategoryApplication;
        _articleApplication = articleApplication;
    }

    public void OnGet()
    {
        ArticleCategories = new SelectList(_articleCategoryApplication.GetCategories(), "Id", "Name");
    }

    public async Task<IActionResult> OnPost(CreateArticle command)
    {
        var result = await _articleApplication.Create(command);
        return RedirectToPage("./Index");
    }
}

ServiceHost/Areas/Administration/Pages/Blog/Article/Edit.cshtml.cs
using BlogMgmt.Application.Contract.Article;
using BlogMgmt.Application.Contract.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Blog.Article;
#nullable disable

public class EditModel : PageModel
{
    private readonly IArticleApplication _articleApplication;
    private readonly IArticleCategoryApplication _articleCategoryApplication;

    public EditArticle Command { get; set; }
    public SelectList ArticleCategories { get; set; }

    public EditModel(IArticleApplication articleApplication,
        IArticleCategoryApplication articleCategoryApplication)
    {
        _articleApplication = articleApplication;
        _articleCategoryApplication = articleCategoryApplication;
    }

    public void OnGet(long id)
    {
        Command = _articleApplication.GetDetails(id);
        ArticleCategories = new SelectList(_articleCategoryApplication.GetCategories(), "Id", "Name");
    }

    public async Task<IActionResult> OnPost(EditArticle command)
    {
        var result = await _articleApplication.Edit(command);
        return RedirectToPage("./Index");
    }
}

ServiceHost/Areas/Administration/Pages/UserAccount/Account/Index.cshtml.cs
using _Framework.Application;
using AccountMgmt.Application.Contract.Account;
using AccountMgmt.Application.Contract.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.UserAccount.Account;
#nullable disable

public class IndexModel : PageModel
{
    private readonly IAccountApplication _accountApplication;
    private readonly IRoleApplication _roleApplication;

    public List<AccountViewModel> Accounts { get; set; }
    public AccountSearchModel SearchModel { get; set; }
    public SelectList Roles { get; set; }

    public IndexModel(IAccountApplication accountApplication,
        IRoleApplication roleApplication)
    {
        _accountApplication = accountApplication;
        _roleApplication = roleApplication;
    }

    public void OnGet(AccountSearchModel searchModel)
    {
        Roles = new SelectList(_roleApplication.GetRoles(), "Id", "Name");
        Accounts = _accountApplication.Search(searchModel);
    }

    public IActionResult OnGetCreate()
    {
        var roles = _roleApplication.GetRoles();
        var model = new CreateAccount() { Roles = roles};
        return Partial("./Create", model);
    }

    public async Task<JsonResult> OnPostCreate(CreateAccount command)
    {
        if (!ModelState.IsValid)
        {
            var failed = new OperationResult();
            failed.Message = "پر کردن تمام فیلدها الزامی است";
            return new JsonResult(failed);
        }
        var result = await _accountApplication.Register(command);

        if (result.IsSucceeded)
        {
            TempData["AccountSubmission"] = result.Message;
        }

        return new JsonResult(result);
    }

    public IActionResult OnGetEdit(long id)
    {
        var account = _accountApplication.GetDetails(id);
        var roles = _roleApplication.GetRoles();
        account.Roles = roles;
        return Partial("./Edit", account);
    }

    public async Task<IActionResult> OnPostEdit(EditAccount command)
    {
        var result = await _accountApplication.Edit(command);

        if (result.IsSucceeded)
        {
            TempData["AccountEdition"] = result.Message;
        }

        return new JsonResult(result);
    }

    public IActionResult OnGetChangePassword(long id)
    {
        var passwdModel = new ChangePassword() { Id = id };
        return Partial("ChangePassword", passwdModel);
    }

    public IActionResult OnPostChangePassword(ChangePassword command)
    {
        var result = _accountApplication.ChangePassword(command);

        if (result.IsSucceeded)
        {
            TempData["PasswordChangeStatus"] = result.Message;
        }

        return new JsonResult(result);
    }
}

ServiceHost/Areas/Administration/Pages/UserAccount/Role/Create.cshtml.cs
using AccountMgmt.Application.Contract.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Areas.Administration.Pages.UserAccount.Role;
#nullable disable

public class CreateModel : PageModel
{
    private readonly IRoleApplication _roleApplication;
    public CreateRole Command { get; set; } = new();

    public CreateModel(IRoleApplication roleApplication)
    {
        _roleApplication = roleApplication;
    }

    public void OnGet()
    {
        
    }

    public IActionResult OnPost(CreateRole command)
    {
        var result = _roleApplication.Create(command);

        if (result.IsSucceeded)
        {
            TempData["RoleSubmission"] = result.Message;
        }

        return RedirectToPage("./Index");
    }
}

ServiceHost/Areas/Administration/Pages/UserAccount/Role/Edit.cshtml.cs
using AccountMgmt.Application.Contract.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Areas.Administration.Pages.UserAccount.Role;
#nullable disable

public class EditModel : PageModel
{
    private readonly IRoleApplication _roleApplication;
    public EditRole Command { get; set; }

    public EditModel(IRoleApplication roleApplication)
    {
        _roleApplication = roleApplication;
    }

    public void OnGet(long id)
    {
        Command = _roleApplication.GetDetails(id);
    }

    public IActionResult OnPost(EditRole command)
    {
        var result = _roleApplication.Edit(command);

        if (result.IsSucceeded)
        {
            TempData["RoleEdition"] = result.Message;
        }

        return RedirectToPage("./Index");
    }
}

ServiceHost/Areas/Administration/Pages/UserAccount/Role/Index.cshtml.cs
using AccountMgmt.Application.Contract.Role;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Areas.Administration.Pages.UserAccount.Role;
#nullable disable

public class IndexModel : PageModel
{
    private readonly IRoleApplication _roleApplication;

    public List<RoleViewModel> Roles { get; set; }

    public IndexModel(IRoleApplication roleApplication)
    {
        _roleApplication = roleApplication;
    }

    public void OnGet()
    {
        Roles = _roleApplication.GetRoles();
    }
}

ServiceHost/Pages/Account.cshtml.cs
using AccountMgmt.Application.Contract.Account;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Pages;
#nullable disable

public class AccountModel : PageModel
{
    private readonly IAccountApplication _accountApplication;

    public AccountModel(IAccountApplication accountApplication)
    {
        _accountApplication = accountApplication;
    }

    public void OnGet()
    {
    }

    public IActionResult OnPostLogin(Login command)
    {
        var result = _accountApplication.Login(command);

        if (!result.IsSucceeded)
        {
            ViewData["LoginErr"] = result.Message;
            ModelState.Clear();
            return Page();
        }

        return RedirectToPage("/Index");
    }

    public ActionResult OnGetLogout()
    {
        _accountApplication.Logout();
        return RedirectToPage("/Index");
    }

    public async Task<IActionResult> OnPostRegister(CreateAccount command)
    {

        var result = await _accountApplication.Register(command);

        if (!result.IsSucceeded)
        {
            ViewData["RegisterErr"] = result.Message;
            return Page();
        }

        return RedirectToPage("/Index");
    }
}

ServiceHost/Areas/Administration/Pages/UserAccount/Account/ChangePassword.cshtml
@using AccountMgmt.Application.Contract.Account
@model ChangePassword

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ویرایش رمز</h4>
</div>

<form asp-page="./Index" asp-page-handler="ChangePassword"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh">

    <div class="modal-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Password" class="control-label">رمز</label>
                    <input type="text" class="form-control" asp-for="Password">
                    <span asp-validation-for="Password" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="RePassword" class="control-label">تکرار رمز</label>
                    <input type="text" class="form-control" asp-for="RePassword">
                    <span asp-validation-for="RePassword" class="error"></span>
                </div>
            </div>
        </div>
    </div>

    <div class="modal-footer">
        <input type="hidden" asp-for="Id" value="@Model.Id" />
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ویرایش</button>
    </div>
</form>

ServiceHost/Areas/Administration/Pages/UserAccount/Account/Create.cshtml
@using AccountMgmt.Application.Contract.Account
@model CreateAccount
@{
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ایجاد کاربر جدید</h4>
</div>

<form asp-page="./Index" asp-page-handler="Create"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">

    <div class="modal-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Fullname" class="control-label">نام</label>
                    <input type="text" class="form-control" asp-for="Fullname">
                    <span asp-validation-for="Fullname" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Username" class="control-label">نام کاربری</label>
                    <input type="text" class="form-control" asp-for="Username">
                    <span asp-validation-for="Username" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Mobile" class="control-label">شماره موبایل</label>
                    <input type="text" class="form-control" asp-for="Mobile">
                    <span asp-validation-for="Mobile" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Password" class="control-label">رمز عبور</label>
                    <input type="text" class="form-control" asp-for="Password">
                    <span asp-validation-for="Password" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="RoleId" class="control-label">نقش</label>
                    <select class="form-control" asp-for="RoleId" asp-items="@(new SelectList(Model.Roles, "Id", "Name"))">
                        <option value="0">-- نقش ها --</option>
                    </select>
                    <span asp-validation-for="RoleId" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="ProfilePhoto" class="control-label">عکس</label>
                    <input type="file" class="form-control" asp-for="ProfilePhoto" accept="image/jpg,image/jpeg,image/png">
                    <span asp-validation-for="ProfilePhoto" class="error"></span>
                </div>
            </div>
        </div>
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ایجاد</button>
    </div>
</form>

ServiceHost/Areas/Administration/Pages/UserAccount/Account/Edit.cshtml
@using AccountMgmt.Application.Contract.Account
@model EditAccount
@{

}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ویرایش کاربر : @Model.Username</h4>
</div>

<form asp-page="./Index" asp-page-handler="Edit"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">

    <div class="modal-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Fullname" class="control-label">نام</label>
                    <input type="text" class="form-control" asp-for="Fullname">
                    <span asp-validation-for="Fullname" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Username" class="control-label">نام کاربری</label>
                    <input type="text" class="form-control" asp-for="Username">
                    <span asp-validation-for="Username" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Mobile" class="control-label">شماره موبایل</label>
                    <input type="text" class="form-control" asp-for="Mobile">
                    <span asp-validation-for="Mobile" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="RoleId" class="control-label">نقش</label>
                    <select class="form-control" asp-for="RoleId" asp-items='@(new SelectList(Model.Roles, "Id", "Name"))'>
                        <option value="0">-- نقش ها --</option>
                    </select>
                    <span asp-validation-for="RoleId" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="ProfilePhoto" class="control-label">عکس</label>
                    <input type="file" class="form-control" asp-for="ProfilePhoto" accept="image/jpg,image/jpeg,image/png">
                </div>
            </div>
        </div>
    </div>

    <div class="modal-footer">
        <input type="hidden" asp-for="Id" value="@Model.Id">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ویرایش</button>
    </div>
</form>

ServiceHost/Areas/Administration/Pages/UserAccount/Account/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "مدیریت کاربران";
}

<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title pull-right">@ViewData["Title"]</h4>
        <p class="pull-left">
            <a class="btn btn-success btn-lg" href="#showmodal=@Url.Page("./Index", "Create")">
                <i class="fa fa-plus"></i>
                ایجاد کاربر جدید
            </a>
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">جستجو در کاربران</h3>
            </div>
            <div class="panel-body">
                <form class="form-inline" role="form" method="get">
                    <div class="form-group">
                        <input class="form-control" asp-for="SearchModel.Fullname" placeholder="نام">
                    </div>
                    <div class="form-group">
                        <input class="form-control" asp-for="SearchModel.Username" placeholder="نام کاربری">
                    </div>
                    <div class="form-group">
                        <input class="form-control" asp-for="SearchModel.Mobile" placeholder="شماره موبایل">
                    </div>
                    <div class="form-group">
                        <select class="form-control" asp-for="SearchModel.RoleId" asp-items="@Model.Roles">
                            <option value="0">-- نقش --</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <button class="btn btn-success waves-effect waves-light m-l-10 m-r-10">جستجو</button>
                        <a class="btn btn-primary waves-effect waves-light m-l-10" asp-page="./Index">مشاهده همه</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        @if (TempData["AccountSubmission"] != null)
        {
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                @TempData["AccountSubmission"]
            </div>
        }
        @if (TempData["AccountEdition"] != null)
        {
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                @TempData["AccountEdition"]
            </div>
        }
        @if (TempData["PasswordChangeStatus"] != null)
        {
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                @TempData["PasswordChangeStatus"]
            </div>
        }
        else
        {
            <div></div>
        }

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">لیست کاربران (@Model.Accounts.Count())</h3>
            </div>
            <div class="panel-body">

                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12 table-responsive">
                        <table data-order='[[ 0, "desc" ]]' id="datatable" class="table table-striped table-bordered ">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>عکس</th>
                                    <th>نام</th>
                                    <th>نام کاربری</th>
                                    <th>موبایل</th>
                                    <th>نقش</th>
                                    <th>تاریخ ایجاد</th>
                                    <th>عملیات</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.Accounts)
                                {
                                    <tr>
                                        <td>@item.Id</td>
                                        <td>
                                            <img src="~/ProductPictures/@item.ProfilePhoto" style="width: 70px; height: 70px" />
                                        </td>
                                        <td>@item.Fullname</td>
                                        <td>@item.Username</td>
                                        <td>@item.Mobile</td>
                                        <td>@item.Role</td>
                                        <td>@item.CreationDate</td>
                                        <td>
                                            <a class="btn btn-warning waves-effect waves-light m-b-5" href="#showmodal=@Url.Page("./Index", "Edit", new { id = item.Id })">
                                                <i class="fa fa-edit"></i> ویرایش
                                            </a>

                                            <a class="btn btn-primary waves-effect waves-light m-b-5" href="#showmodal=@Url.Page("./Index", "ChangePassword", new { id = item.Id })">
                                                <i class="fa fa-key"></i> تغییر رمز
                                            </a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/AdminTheme/assets/datatables/jquery.dataTables.min.js"></script>
    <script src="~/AdminTheme/assets/datatables/dataTables.bootstrap.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#datatable').dataTable();
        });
    </script>
}